version: "2.0"

services:
  nginx:
    image: nginx:1.17
    volumes:
      - "${APP_DIR}:/var/www/html:ro"
      - "${NGINX_CONF_DIR}:/etc/nginx/conf.d"
    depends_on:
      - php
      - phpmyadmin
      - mysql
    networks:
      - server
      - nginx-proxy-network
      - database
    environment:
      - VIRTUAL_HOST=${DOMAINS},${PMA_DOMAIN}
      - LETSENCRYPT_HOST=${DOMAINS},${PMA_DOMAIN}

  php:
    image: acrossoffwest/php73-for-scheduler:0.0.0
    volumes:
      - "${APP_DIR}:/var/www/html"
      - "./supervisor:/etc/supervisor"
      - "./cron.d:/etc/cron.d"
      - "./php/custom.ini:/usr/local/etc/php/conf.d/custom.ini"
    depends_on:
      - mysql
    networks:
      - database
      - server

  redis:
    image: 'bitnami/redis:latest'
    environment:
      - ALLOW_EMPTY_PASSWORD=no
      - REDIS_PASSWORD="${REDIS_PASSWORD}"
    networks:
      - database

  mysql:
    image: mysql:5.7
    volumes:
      - /var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: "${DB_ROOT_PASSWORD}"
      MYSQL_DATABASE: "${DB_NAME}"
      MYSQL_USER: "${DB_USERNAME}"
      MYSQL_PASSWORD: "${DB_PASSWORD}"
    networks:
      - database

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      PMA_HOST: mysql
    depends_on:
      - mysql
    networks:
      - database

networks:
  database:
  server:
  nginx-proxy-network:
    external:
      name: reverseproxy_default
